openapi: "3.0.3"
info:
  title: "test_task_ktor API"
  description: "test_task_ktor API"
  version: "1.0.0"
servers:
- url: "https://localhost:88"
paths:
  /api/counters:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Map_String"
    post:
      description: ""
      parameters:
      - name: "name"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "value"
        in: "query"
        required: false
        schema:
          type: "number"
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                type: "object"
  /api/counters/{name}:
    delete:
      description: ""
      parameters:
      - name: "name"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
    get:
      description: ""
      parameters:
      - name: "name"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Map_String"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
  /api/counters/increment:
    patch:
      description: ""
      parameters:
      - name: "name"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int64"
components:
  schemas:
    Map:
      type: "object"
      properties: {}
    Map_String:
      type: "string"